# Site settings
title: gaogao
email: gaogao1130@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hello world
baseurl: "/learning-jekyll" # the subpath of your site, e.g. /blog/
url: "http://gaogao1030.github.io" # the base hostname & protocol for your site
twitter_username: gaogao1030
github_username:  gaogao1030

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: 'rouge'

timezone: '+0800'
permalink: '/:categories/:year/:month/:day/:title'

keep_files: [".git","CNAME",".nojekyll"]

paginate: 10
jekyll-archives:
  enabled: all

gems:
  - jekyll-archives
