# Site settings
title: gaogao
email: gaogao1130@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hello world
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gaogao1130@gmail.com
github_username:  gaogao1130@gmail.com

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: 'rouge'

timezone: '+0800'
permalink: '/:categories/:year/:month/:day/:title'

